name: Flutter CI
on: 
  push:
    branches: 
      - 'master'

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: macOS-latest
    needs: prepare
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Setup fluter
        uses: subosito/flutter-action@v1.4.0
        
      - name: Set up test tools
        run: |
          flutter pub get
          flutter pub global activate dart_dot_reporter
          flutter pub global activate junitreport
          pip install junit2html
          
      - name: Test
        run: |
          export PATH=$PATH:${FLUTTER_HOME}/bin/cache/dart-sdk/bin
          export PATH=$PATH:${FLUTTER_HOME}/.pub-cache/bin
          ./test.sh
      
      - name: Activate test results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: test-reports
        
      - name: Slack notification
        if: always()
        uses: homoluctus/slatify@master
        with:
          type: ${{ job.status }}
          job_name: '*build and DebugCheck*'
          channel: '#general'
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
